image: docker:19.03.6

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.6

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t luxsoft .
    - docker run luxsoft